# Generated by Django 4.2.7 on 2024-01-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appl', '0002_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
